### ISSUE TITLE
安装磁盘控制器后nas-pvc方式挂载失败

### ISSUE THREAD

**Issue by einsone** [AliyunContainerService/serverless-k8s-examples#24]
部署磁盘控制器后产生了两个Pod
1. 磁盘控制器pod: `alicloud-disk-controller-xxx`，正常运行

2. CSI插件pod: `csi-nasplugin-xxx`，一直处于`pending`状态

使用nas-pvc.yaml执行测试时挂载失败， 其他两种方式均可挂载成功. nas-nfsvolume.yaml和nas-flexvolume.yaml

错误日志:

MountVolume.SetUp failed for volume "persistent-storage" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/94f5d109-71d2-4091-8eee-c20abbcd6f09/volumes/kubernetes.io~nfs/persistent-storage --scope -- mount -t nfs xxxxxx.cn-chengdu.nas.aliyuncs.com:/nfs/ /var/lib/kubelet/pods/94f5d109-71d2-4091-8eee-c20abbcd6f09/volumes/kubernetes.io~nfs/persistent-storage Output: Running scope as unit run-971.scope. mount.nfs: **access denied** by server while mounting xxxx.cn-chengdu.nas.aliyuncs.com:/nfs/

**Comment by jovizhangwei** [comment]
@einsone 你部署的是csi？ASK还不支持CSI，因为ECI无法支持特权模式

**Comment by jovizhangwei** [comment]
使用flexvolume静态挂载nas是支持的。
