### ISSUE TITLE
创建 serverless 集群的时候没有创建 privatezone，之后还能配置内部集群域名解析吗

### ISSUE THREAD

**Issue by domgoer** [AliyunContainerService/serverless-k8s-examples#25]

**Comment by jovizhangwei** [comment]
可以的。@domgoer 
麻烦加入ASK交流群，里面详细解答。https://help.aliyun.com/document_detail/109974.html?spm=a2c4g.11186623.6.1039.26252459dPmIuJ

**Comment by domgoer** [comment]
感谢
